### ISSUE TITLE
Enhancement - Ordering of pages

### ISSUE THREAD

**Issue by speters217** [masranber/MaintenanceBuddy#10]
**Summary:** 
The current ordering of pages does not follow the natural flow a user will use to navigate the app.

**Description:**
When a user logs in, they land on the records page. However, they are unable to do anything on the records page unless they have first selected a car on the garage page. I would recommend making the landing page the garage page, and perhaps also making the garage page appear before the records page on the navigation panel in the bottom.

**Severity:** 
Medium. The current configuration is disorienting, however it is easy to navigate once you understand the functionality of each page.

**Comment by masranber** [comment]
Fixed! Thanks
