### ISSUE TITLE
Enhancement - No error message with invalid signup

### ISSUE THREAD

**Issue by andrew-j-frank** [masranber/MaintenanceBuddy#11]
**Summary:** If you click the signup button without putting in valid data and click sign up, nothing happens.

**Description:**
 Examples of invalid data include an email not in email format, or a password less than 8 characters.

To reproduce: 
1. Open the maintenance buddy app
2. Click sign up
3. Without typing anything in, click sign up
4. Nothing happens

The user may think they are putting in valid information for signup, and then are not able to sign up. This affects the user experience and could cause frustration to the user. I suggest creating a popup or message that explains to the user which sign up field is invalid.

**Severity:** Medium, as users only sign up once, but first impressions matter for the user, and this could happen fairly frequently.

**Comment by masranber** [comment]
Fixed! Thanks
