### ISSUE TITLE
Enhancement - Undescriptive error message when signing up a user that already exists

### ISSUE THREAD

**Issue by andrew-j-frank** [masranber/MaintenanceBuddy#12]
**Summary:** If you click the signup button with information on an existing user, the error message is very vague.

**Description:**
To reproduce: 
1. Open the maintenance buddy app
2. Click sign up
3. Enter in the information of an existing user
4. Click sign up
5. The error message given is "An unknown error has occurred. Please try again later."

This error message is undescriptive. I suggest making the error tell the user that this user already exists and to go to the sign in page to login. Also, I recommend making the error message stand out more since currently it is small and light grey and may be hard to notice.

**Severity:** Low, as most users will not try to sign up as an existing user.

**Comment by masranber** [comment]
Fixed! Thanks
