### ISSUE TITLE
Bug - Unable to add to garage

### ISSUE THREAD

**Issue by mtru32** [masranber/MaintenanceBuddy#14]
Summary: Clicking the 'Add Event' button with filled-out fields has no effect.

Description: After filling out all of the fields for 'Add Vehicle' on the garage page, clicking 'Add Event' does nothing. Additionally, there is no feedback, so a user won't know if they are missing a field, filling one out incorrectly, or if the service failed on its own.

Severity: High. Users need to be able to add vehicles, otherwise, the app is unusable.

**Comment by masranber** [comment]
Fixed! Thanks for the feedback.
