### ISSUE TITLE
Enhancement - Change Add Event button to Add Vehicle in the add vehicle form

### ISSUE THREAD

**Issue by andrew-j-frank** [masranber/MaintenanceBuddy#15]
**Summary:** In the add vehicle form in the garage, the button to submit the form says Add Event, which may be confusing to the user.

**Description:**
To reproduce: 
1. Log in
2. Go to garage
3. Press the add button
4. The button to submit the form says Add Event

This may confuse the user. They think they are adding a vehicle to the garage, but the button says Add Event. They might not know what the form is for since it says add vehicle at the top but add event to submit the form.

**Severity:** Low, it doesn't affect functionality but is an inconsistency that is worth fixing.

**Comment by masranber** [comment]
Fixed! Thanks for the suggestion.
