### ISSUE TITLE
Enhancement - Keyboard changes page layout

### ISSUE THREAD

**Issue by mtru32** [masranber/MaintenanceBuddy#16]
Summary: On the garage page the [records, calendar, garage] buttons are above the keyboard.

Description: When trying to fill out fields, the navigation buttons are pushed above the keyboard. This clutters the screen and could cause a user to click off to a different page when trying to select another vehicle field.

Severity: Low. This is mostly a cosmetic issue though a user could get frustrated if they accidentally navigate to a different page more than once.

**Comment by masranber** [comment]
Fixed! Thanks for the suggestion.
