### ISSUE TITLE
Bug - Default name visible on Garage page

### ISSUE THREAD

**Issue by speters217** [masranber/MaintenanceBuddy#4]
**Summary:** 
Default name visible on Garage page.

**Description:** 
When clicking the "Garage" button, for a brief second it says "Name's Garage" before replacing with the user's name.

**Severity:** 
Low. This likely won't impact users at all. However, it is a good idea to fix this if possible, since it will make the app look more polished.

**Comment by masranber** [comment]
Fixed! Thanks for the feedback.
