### ISSUE TITLE
Bug - Button not visible on Garage page

### ISSUE THREAD

**Issue by speters217** [masranber/MaintenanceBuddy#5]
**Summary:** 
In the Add Vehicle form on the Garage page, the button below "Add Event" isn't visible.

**Description:** 
The top of the button can be seen, however no text can be read.

**Severity:** 
High. Without being able to see this button, there is no way of knowing its intended purpose. Users might assume that the button above it is the one that needs to be clicked, when that button may not be the correct one.

**Comment by masranber** [comment]
Fixed! Thanks for the feedback.
