### ISSUE TITLE
Enhancement - New Service Record button visible when there is no car selected

### ISSUE THREAD

**Issue by speters217** [masranber/MaintenanceBuddy#7]
**Summary:** 
New Service Record button visible when there is no car selected.

**Description:**
When a car is not selected, the New Service Record button is still visible. Clicking it does nothing, and no further instructions are provided.

**Severity:** 
Medium. The user might be confused by the lack of response from their input. You may want to consider removing the button if the user has not selected a car, or making the "Please Select a Vehicle" text at the top of the screen turn red.

**Comment by masranber** [comment]
Fixed!
