### ISSUE TITLE
Bug - New Service Record form doesn't close after submitting

### ISSUE THREAD

**Issue by speters217** [masranber/MaintenanceBuddy#8]
**Summary:** 
New Service Record form doesn't close after submitting.

**Description:**
After filling out the New Service Record form and submitting, the form still remains visible and the user gets no feedback. After manually closing the page and going back to the records page, a service record was added for every time I hit the submit button.

**Severity:** 
High. The user should receive feedback when they click on the submit button. This could be as simple as returning them to the records page.

**Comment by masranber** [comment]
Fixed!
